FROM node:18-alpine
EXPOSE 3000
RUN mkdir /app
WORKDIR /app

COPY package.json index.js /app/

RUN apk update
RUN apk add kubectl

CMD ["node", "index.js"]

#docker build -t demo:v1 .
#kind load docker-image demo:v1 --name devops
